openapi: 3.0.3
info:
  title: Decisions Runtime Builder
  contact:
    name: SAS Developers
    url: https://developer.sas.com
    email: devex@sas.com
  description: The Decisions Runtime Builder API provides functions that enable you to update the SAS Container Runtime binary files in a published image.
  version: "1"
  license:
    name: SAS Institute
    url: https://support.sas.com/techsup/license/index.html
servers:
  - url: https://example.com/decisionsRuntimeBuilder
    description: This is an example of a base URL.
tags:
  - name: Root
    description: Contains the operations for the Root resource.
  - name: Update
    description: Contains the operations for the update resources.
components:
  headers:
    Sas-Service-Response-Flag:
      description: Indicates whether the response is from a SAS service.
      schema:
        type: boolean
      example: true
  schemas:
    scrUpdateRequest:
      title: Update Request
      description: The parameters for the update request.
      type: object
      properties:
        publishDestination:
          type: string
          description: The publish destination of the SAS Container Runtime image.
        publishTag:
          type: string
          description: The publish tag (revision) to assign to the updated SAS Container Runtime image.
    scrCommandResult:
      title: Update Result
      description: The results of the update request.
      type: object
      properties:
        command:
          type: string
          description: The name of the command that was run.
        status:
          type: string
          description: The status of the command that was run.
        log:
          type: string
          description: The logs that were generated by the command that was run.
    api:
      title: API
      description: The list of links to top-level resources and operations available from the root of the API.
      x-sas-media-type:
        name: application/vnd.sas.api
        version: 1
      required:
        - version
        - links
      properties:
        version:
          type: integer
          description: The version number of the API representation. This is version 1.
          minimum: 1
        links:
          description: The API's top-level links.
          type: array
          items:
            $ref: "#/components/schemas/link"
    baseCollection2:
      title: Base Collection
      description: This is a base schema used to define paginated collections of resources. This base schema is extended by other schemas in APIs by adding an 'items' array property. These extensions define the application/vnd.sas.collection media type (version 2)
      properties:
        name:
          type: string
          description: The name of the collection.
        start:
          type: integer
          description: The zero-based index of the first item in the collection.
          format: int64
        limit:
          type: integer
          description: The number of items that were requested for the collection.
        count:
          type: integer
          description: If populated indicates the number of items in the collection.
          format: int64
        accept:
          type: string
          description: A space-delimited list of media types from which an `Accept` header may be constructed.
        links:
          type: array
          description: The links that apply to the collection.
          items:
            $ref: "#/components/schemas/link"
        version:
          type: integer
          description: The version number of the collection representation. This representation is version 2.
    error2:
      title: Error
      type: object
      description: The representation of an error.
      x-sas-media-type:
        name: application/vnd.sas.error
        version: 2
      required:
        - httpStatusCode
        - version
      properties:
        message:
          type: string
          description: The message for the error.
        id:
          type: string
          description: The string ID for the error.
        errorCode:
          type: integer
          description: The numeric ID for the error.
        httpStatusCode:
          type: integer
          description: The HTTP status code for the error.
        details:
          type: array
          description: Messages that provide additional details about the cause of the error.
          items:
            type: string
        remediation:
          type: string
          description: A message that describes how to resolve the error.
        errors:
          type: array
          description: Any additional errors that occurred.
          items:
            $ref: "#/components/schemas/error2"
        links:
          type: array
          description: The links that apply to the error.
          items:
            $ref: "#/components/schemas/link"
        version:
          type: integer
          description: The version number of the error representation. This representation is version 2.
    link:
      title: Link
      type: object
      description: A link to a related operation or resource.
      required:
        - rel
      properties:
        method:
          type: string
          description: The HTTP method for the link.
        rel:
          type: string
          description: The relationship of the link to the resource.
        uri:
          type: string
          description: The relative URI for the link.
        href:
          type: string
          description: The URL for the link.
        title:
          type: string
          description: The title for the link.
        type:
          type: string
          description: The media type or link type for the link.
        itemType:
          type: string
          description: If this is a link to a container, `itemType` is the media type or link type for the items in the container.
        responseType:
          type: string
          description: The media type or link type of the response body for a `PUT`, `POST`, or `PATCH` operation.
        responseItemType:
          type: string
          description: The media type or link type of the items in the response body for a `PUT`, `POST`, or `PATCH` operation.
  examples:
    ScrUpdateRequest:
      description: Update a SAS Container Runtime published image request.
      value:
        imageURI: registry.myserver.com/scr-pipeline-apps/autopurchasedec1_1:3
        publishDestination: scr-pipeline-apps
        publishTag: "1.5"
    root:
      description: List of top-level links.
      value:
        version: 1
        links:
          - method: GET
            rel: decisionsRuntimeBuilderRoot
            href: /decisionsRuntimeBuilder
            uri: /decisionsRuntimeBuilder
            type: application/vnd.sas.api
          - method: GET
            rel: updateScr
            href: /decisionsRuntimeBuilder/update
            uri: /decisionsRuntimeBuilder/update
            responseType: application/vnd.sas.microanalytic.module
    ScrCommandResult:
      description: Update a SAS Container Runtime published image response.
      value:
        command: Update
        log: >
          [0m[0000] Resolved base name cr.myserver.com/viya-4-x64_oci_linux_2-docker-testready/sas-decisions-runtime-components:1.10.8-20220625.1656140924715 to base 

          [0m[0000] Resolved base name registry.myserver.com/scr-pipeline-apps/autopurchasedec1_1:3 to modelsource 

          [0m[0000] Retrieving image manifest cr.myserver.com/viya-4-x64_oci_linux_2-docker-testready/sas-decisions-runtime-components:1.10.8-20220625.1656140924715 

          [0m[0000] Retrieving image cr.myserver.com/viya-4-x64_oci_linux_2-docker-testready/sas-decisions-runtime-components:1.10.8-20220625.1656140924715 from registry cr.myserver.com 

          [0m[0001] Retrieving image manifest registry.myserver.com/scr-pipeline-apps/autopurchasedec1_1:3 

          [0m[0001] Retrieving image registry.myserver.com/scr-pipeline-apps/autopurchasedec1_1:3 from registry registry.myserver.com 

          [0m[0001] Retrieving image manifest cr.myserver.com/viya-4-x64_oci_linux_2-docker-testready/sas-decisions-runtime-base:1.28.8-20220625.1656140894246 

          [0m[0001] Retrieving image cr.myserver.com/viya-4-x64_oci_linux_2-docker-testready/sas-decisions-runtime-base:1.28.8-20220625.1656140894246 from registry cr.myserver.com 

          [0m[0002] Built cross stage deps: map[0:[/oracle] 1:[/modules]] 

          [0m[0002] Retrieving image manifest cr.myserver.com/viya-4-x64_oci_linux_2-docker-testready/sas-decisions-runtime-components:1.10.8-20220625.1656140924715 

          [0m[0002] Returning cached image manifest              

          [0m[0002] Executing 0 build triggers                   

          [0m[0013] Saving file oracle for later use             

          [0m[0014] Deleting filesystem...                       

          [0m[0015] Retrieving image manifest registry.myserver.com/scr-pipeline-apps/autopurchasedec1_1:3 

          [0m[0015] Returning cached image manifest              

          [0m[0015] Executing 0 build triggers                   

          [0m[0030] Saving file modules for later use            

          [0m[0030] Deleting filesystem...                       

          [0m[0031] Retrieving image manifest cr.myserver.com/viya-4-x64_oci_linux_2-docker-testready/sas-decisions-runtime-base:1.28.8-20220625.1656140894246 

          [0m[0031] Returning cached image manifest              

          [0m[0031] Executing 0 build triggers                   

          [0m[0031] Unpacking rootfs as cmd COPY --from=modelSource --chown=sas:sas /modules /modules requires it. 

          [0m[0044] LABEL model container image                  

          [0m[0044] Applying label model=container image         

          [0m[0044] ENV SAS_SCR_APP_PATH=autopurchasedec1_1      

          [0m[0044] COPY --from=modelSource --chown=sas:sas /modules /modules 

          [0m[0044] Taking snapshot of files...                  

          [0m[0044] COPY --from=base /oracle /                   

          [0m[0044] Taking snapshot of files...                  

          [0m[0049] ENV ORACLE_HOME=/usr/lib/oracle/19.13/client64 ORAENV_ASK=NO SASORA=V9 TWO_TASK=ORACLE_SID 

          [0m[0049] ENV LD_LIBRARY_PATH=/opt/scr/viya/home/SASFoundation/utilities/bin:/opt/scr/viya/home/SASFoundation/sasexe:/usr/lib64:/usr/lib/oracle/19.13/client64/lib 

          [0m[0049] Pushing image to registry.myserver.com/scr-pipeline-apps/autopurchasedec1_1:1.5 

          [0m[0055] Pushed registry.myserver.com/scr-pipeline-apps/autopurchasedec1_1@sha256:a8f1844417f082d88fed31000e8252d4174aa5916d54a6016c462b30111948c2 
        status: Success
paths:
  /:
    get:
      summary: Get a list of top-level links
      description: Returns a list of links to the top-level collections that are surfaced through the API.
      operationId: root
      tags:
        - Root
      responses:
        "200":
          description: The request succeeded. A collection of link objects was returned.
          headers:
            Sas-Service-Response-Flag:
              $ref: "#/components/headers/Sas-Service-Response-Flag"
          content:
            application/vnd.sas.api+json:
              schema:
                $ref: "#/components/schemas/api"
              examples:
                default:
                  $ref: "#/components/examples/root"
            application/json:
              schema:
                $ref: "#/components/schemas/api"
              examples:
                default:
                  $ref: "#/components/examples/root"
  /update:
    post:
      tags:
        - Update
      summary: Update a SAS Container Runtime published image
      description: Updates the SAS Container Runtime binary files in a published image.
      operationId: createUpdateScr
      requestBody:
        content:
          application/vnd.sas.scr.update.request+json:
            schema:
              $ref: "#/components/schemas/scrUpdateRequest"
            examples:
              default:
                description: Update a published image.
                value:
                  imageURI: registry.myserver.com/scr-pipeline-apps/autopurchasedec1_1:3
                  publishDestination: scr-pipeline-apps
                  publishTag: "1.5"
          application/json:
            schema:
              $ref: "#/components/schemas/scrUpdateRequest"
            examples:
              default:
                $ref: "#/components/examples/ScrUpdateRequest"
        description: updateReq
        required: true
      responses:
        "201":
          description: The SAS Container Runtime binary files were updated in the image.
          headers:
            Location:
              description: /decisionsRuntimeBuilder
              schema:
                type: string
            ETag:
              description: A tag that identifies the revision of this object.
              schema:
                type: string
          content:
            application/vnd.sas.scr.update.request+json:
              schema:
                $ref: "#/components/schemas/scrCommandResult"
              examples:
                default:
                  $ref: "#/components/examples/ScrCommandResult"
            application/json:
              schema:
                $ref: "#/components/schemas/baseCollection2"
              examples:
                default:
                  $ref: "#/components/examples/ScrCommandResult"
        "400":
          description: The request was invalid. The image was not updated.
          content:
            application/vnd.sas.scr.update.request+json:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                default:
                  description: Bad request.
                  value:
                    httpStatusCode: 400
                    version: 2
            application/json:
              schema:
                $ref: "#/components/schemas/error2"
              examples:
                default:
                  description: Bad request.
                  value:
                    httpStatusCode: 400
                    version: 2
